.git/
.github/
.venv/
venv/
__pycache__/

backend/
monitoring/
data/
docs/
scripts/
training/
artifacts/

mlflow.db
mlartifacts/

frontend/node_modules/
frontend/dist/
frontend/.env

.vscode/
.idea/
.DS_Store
Thumbs.db
